# Generated by Django 4.2.7 on 2026-01-04 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_document', models.FileField(upload_to='beneficiary_docs/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='beneficiary_docs/')),
                ('death_certificate', models.FileField(blank=True, null=True, upload_to='beneficiary_docs/')),
                ('death_certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='beneficiary_docs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deceased', 'Deceased'), ('removed', 'Removed')], default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
