# Generated by Django 4.2.7 on 2026-02-02 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='percentage_allocation',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of contributions allocated to this beneficiary (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
