# Generated by Django 4.2.7 on 2026-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_beneficiary_percentage_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
