# Generated by Django 4.2.7 on 2026-02-04 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_add_uuid_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
