# Generated by Django 4.2.7 on 2026-02-10 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_make_uuid_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='id',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
