# Generated by Django 4.2.7 on 2026-06-25 18:27

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_remove_beneficiary_id_alter_beneficiary_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, storage=apps.documents.storage.SupabaseStorage(), upload_to='beneficiary_docs/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, storage=apps.documents.storage.SupabaseStorage(), upload_to='beneficiary_docs/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='death_certificate',
            field=models.FileField(blank=True, null=True, storage=apps.documents.storage.SupabaseStorage(), upload_to='beneficiary_docs/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='identity_document',
            field=models.FileField(storage=apps.documents.storage.SupabaseStorage(), upload_to='beneficiary_docs/'),
        ),
    ]
