[pytest]
DJANGO_SETTINGS_MODULE = advance_company.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Test *Tests
python_functions = test_*
addopts =
    --cov=apps
    --cov-report=html:htmlcov
    --cov-report=term-missing
    --cov-fail-under=60
    -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
