# Generated by Django 4.2.7 on 2026-01-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_created', 'Deposit Created'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('beneficiary_added', 'Beneficiary Added'), ('beneficiary_verified', 'Beneficiary Verified'), ('beneficiary_deceased', 'Beneficiary Deceased'), ('system', 'System Notification')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive notifications via SMS')),
                ('push_enabled', models.BooleanField(default=True, help_text='Receive push notifications in-app')),
                ('deposit_notifications', models.BooleanField(default=True, help_text='Notifications about deposits')),
                ('application_notifications', models.BooleanField(default=True, help_text='Notifications about applications')),
                ('document_notifications', models.BooleanField(default=True, help_text='Notifications about documents')),
                ('beneficiary_notifications', models.BooleanField(default=True, help_text='Notifications about beneficiaries')),
                ('monthly_reports', models.BooleanField(default=True, help_text='Receive monthly financial reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
