# Generated by Django 4.2.7 on 2026-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_created', 'Deposit Created'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('document_deleted', 'Document Deleted'), ('beneficiary_added', 'Beneficiary Added'), ('beneficiary_verified', 'Beneficiary Verified'), ('beneficiary_deceased', 'Beneficiary Deceased'), ('beneficiary_deleted', 'Beneficiary Deleted'), ('system', 'System Notification')], max_length=50),
        ),
    ]
