# Generated by Django 4.2.7 on 2026-01-06 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
