# Generated by Django 4.2.7 on 2026-01-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_deposit_approved_at_deposit_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_response_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='financial_d_user_id_9dd578_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='financial_d_mpesa_c_f797ca_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['transaction_reference'], name='financial_d_transac_de4be5_idx'),
        ),
    ]
