export interface Beneficiary {
  uuid: string;
  user: number;
  user_name?: string;
  user_email?: string;
  user_phone?: string;
  name: string;
  relation: 'spouse' | 'child' | 'parent' | 'sibling' | 'other';
  relation_display?: string;
  age: number;
  gender: 'M' | 'F' | 'O';
  gender_display?: string;
  phone_number?: string;
  profession?: string;
  salary_range?: string;
  percentage_allocation: number;
  identity_document?: string;
  identity_document_url?: string;
  birth_certificate?: string;
  birth_certificate_url?: string;
  death_certificate?: string;
  death_certificate_url?: string;
  death_certificate_number?: string;
  additional_documents?: string;
  additional_documents_url?: string;
  status: 'active' | 'deceased' | 'removed';
  status_display?: string;
  verification_status: 'verified' | 'pending' | 'rejected';
  verification_status_display?: string;
  created_at: string;
  updated_at: string;
}
