# Generated by Django 4.2.7 on 2026-01-15 16:11

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_backup_codes_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='device_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG, GIF (Max 5MB)', null=True, upload_to=apps.accounts.models.user_profile_photo_path),
        ),
    ]
