# Generated by Django 4.2.7 on 2026-06-25 18:27

import apps.accounts.models
import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_biometricauthlog_id_remove_biometricdevice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, null=True, storage=apps.documents.storage.SupabaseStorage(), upload_to='identity_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG, GIF (Max 5MB)', null=True, storage=apps.documents.storage.SupabaseStorage(), upload_to=apps.accounts.models.user_profile_photo_path),
        ),
    ]
