# Generated by Django 4.2.7 on 2026-01-12 10:07

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/'
                                #  validators=[apps.documents.models.validate_document_file]
                                 ),
        ),
    ]
