# Generated by Django 4.2.7 on 2026-02-02 06:29

import apps.documents.storage
import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=apps.documents.storage.CleanMediaCloudinaryStorage(), upload_to='documents/', validators=[apps.documents.validators.validate_document_file]),
        ),
    ]
