# Generated by Django 4.2.7 on 2026-02-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reports.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('DELETED', 'Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEEDBACK', 'Feedback'), ('COMPLAINT', 'Complaint'), ('REQUEST', 'Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
