# Generated by Django 4.2.7 on 2026-02-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_date_from_report_date_to_report_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEEDBACK', 'Feedback'), ('COMPLAINT', 'Complaint'), ('REQUEST', 'Request'), ('FINANCIAL', 'Financial Report')], max_length=20),
        ),
    ]
