# Generated by Django 4.2.7 on 2026-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEEDBACK', 'Feedback'), ('COMPLAINT', 'Complaint'), ('REQUEST', 'Request'), ('FINANCIAL', 'Financial Report'), ('COMPENSATORY', 'Compensatory Report'), ('ACTIVITY', 'Activity Log')], max_length=20),
        ),
    ]
