# Generated by Django 4.2.7 on 2026-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
